/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_adivinador;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Preguntas extends javax.swing.JFrame {
   
    public static Arbol_Binario tree; //Necesito que sea estatico y publico para poder pasarlo de vuelta a menu
    public boolean terminar = false;
    private Nodo nodoActual;
    /**
     * Creates new form Preguntas
     * @param nuevo
     */
    public Preguntas(Arbol_Binario nuevo) {
        initComponents();
        GenioGana.setVisible(false);
        GenioPierde.setVisible(false);
        tree = nuevo; //El arbol que le llegua de Menu
        this.nodoActual = tree.getRoot(); //Se actualiza el nodo actual
        Titulo.setText("Respondele al Genio");
        if (tree.Hoja(nodoActual)) { //Se ve si el nodo actual es una hoja
            Preguntas.setText("¿Piensas en un/a: "+ nodoActual.getData()+"?"); 
        } else{
            Preguntas.setText("¿Dime, acaso tu animal: "+ nodoActual.getData()+"?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Preguntas = new javax.swing.JLabel();
        Si = new javax.swing.JButton();
        No = new javax.swing.JButton();
        Genio = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        GenioGana = new javax.swing.JLabel();
        GenioPierde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Preguntas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Preguntas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Preguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 193, 542, 71));

        Si.setBackground(new java.awt.Color(255, 204, 204));
        Si.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Si.setText("Si");
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        getContentPane().add(Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 305, 59, -1));

        No.setBackground(new java.awt.Color(255, 204, 204));
        No.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        getContentPane().add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 305, -1, -1));

        Genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_adivinador/Akinator/Genio2.1.png"))); // NOI18N
        getContentPane().add(Genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 0, 460, 492));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Respondele al Genio");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 83, 542, -1));

        GenioGana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_adivinador/Akinator/Genio3.1.png"))); // NOI18N
        getContentPane().add(GenioGana, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 460, 490));

        GenioPierde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_adivinador/Akinator/GenioPierde.png"))); // NOI18N
        getContentPane().add(GenioPierde, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 460, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_adivinador/Akinator/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:
        if (terminar != true) {
        if (tree.Hoja(nodoActual)) { //Si es una hoja, el genio adivino el animal
            Titulo.setText("¡¡Soy el más grande!!");
            Genio.setVisible(false);
            GenioGana.setVisible(true);
            terminar = true;
        } else {
            nodoActual = nodoActual.getRight(); // Se pasa a preguntar la informacion a la derecha
            if (tree.Hoja(nodoActual)) {
                Preguntas.setText("¿Piensas en un/a: "+ nodoActual.getData()+"?"); 
            } else
                Preguntas.setText("¿Dime, acaso tu animal: "+ nodoActual.getData()+"?");
        }
        }
    }//GEN-LAST:event_SiActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        if (terminar != true) {
            
        String animalN = "", animalV = nodoActual.getData(), caracteristica = "";
        boolean flag = true, flag2 = true;
        int caso2 = 0;
        
        if (tree.Hoja(nodoActual)) { //Se ve si es hoja 
            
            Titulo.setText("Me he equivocado");
            Genio.setVisible(false);
            GenioPierde.setVisible(true);
            terminar = true;
            //Se preguntan la informacion
            if (JOptionPane.showConfirmDialog(null, ("¿Podría ayudarme a mejorar mis conocimietos?"), "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            while( flag ){ 
            try{
                
                animalN = JOptionPane.showInputDialog("¿Cúal era tu animal?");
                if (animalN.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, diga el animal en el cual penso");
                } else
                    flag = false;
                
            } catch( NullPointerException e){
                JOptionPane.showMessageDialog(null, "Por favor, diga el animal en el cual penso");
            }
            }
            
            while (flag2) {
                try{
                
                caracteristica = JOptionPane.showInputDialog("¿Qué diferencia a su nuevo animal de un/a "+animalV+"?");
                if (caracteristica.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, diga la caracteristica del animal");
                } else
                    flag2 = false;
                
                } catch( NullPointerException e){
                    JOptionPane.showMessageDialog(null, "Por favor, diga la caracteristica del animal");
                }
            }
            
            flag = true; flag2 = true;
            
            tree.agregarAnimal(animalN, caracteristica, nodoActual); //Se agrega el nuevo animal
            
            while(flag){ //Se pregunta si la persona tambien pensaria en el animal que el genio dio si supiera lo mismo que el
                try{
                    caso2 = JOptionPane.showConfirmDialog(null, ("Según la preguntado, ¿Usted pensaría en un/a"+ animalV +"?"), "", JOptionPane.YES_NO_OPTION);
                    if(!Integer.toString(caso2).isEmpty())
                        flag = false;
                } catch(NullPointerException e){
                    JOptionPane.showMessageDialog(null, "Por favor, responda a la pregunta");
                }
            }
            
            if (caso2 == JOptionPane.NO_OPTION){ //Si no pensaria lo mismo, se procede al caso 2, preguntando la informacion necesaria
                    
               flag = true;
               nodoActual = tree.encontrar(animalV, tree.getRoot());
               
            while( flag ){ 
            try{
                
                animalN = JOptionPane.showInputDialog("¿Cúal diria usted que es el animal según lo preguntado?");
                if (animalN.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, diga el animal en el cual penso");
                } else
                    flag = false;
                
            } catch( NullPointerException e){
                JOptionPane.showMessageDialog(null, "Por favor, diga el animal en el cual penso");
            }
            }
            
            while (flag2) {
                try{
                
                caracteristica = JOptionPane.showInputDialog("¿Qué diferencia a este animal de un/a "+animalV+"?");
                if (caracteristica.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, diga la caracteristica del animal");
                } else
                    flag2 = false;
                
                } catch( NullPointerException e){
                    JOptionPane.showMessageDialog(null, "Por favor, diga la caracteristica del animal");
                }
            }
            
            tree.agregarAnimal(animalN, caracteristica, nodoActual); //Se agrega ese nuevo animal que tiene parecidos al viejo
            
            }
            
        } } else {
            nodoActual = nodoActual.getLeft();
            if (tree.Hoja(nodoActual)) {
                Preguntas.setText("¿Piensas en un/a: "+ nodoActual.getData()+"?"); 
            } else
                Preguntas.setText("¿Dime, acaso tu animal: "+ nodoActual.getData()+"?");
        }
        }
    }//GEN-LAST:event_NoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genio;
    private javax.swing.JLabel GenioGana;
    private javax.swing.JLabel GenioPierde;
    private javax.swing.JButton No;
    private javax.swing.JLabel Preguntas;
    private javax.swing.JButton Si;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
